---
version: "3"
services:
  haproxy:
    build: ./haproxy
    networks:
      main:
        aliases:
          - haproxy

  consul-server:
    image: consul
    environment:
    - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    command: consul agent -server -retry-join=haproxy -bootstrap-expect=3 --data-dir=/tmp/data
    networks:
      main:
        aliases:
          - consul-server

networks:
  main: